# Generated by Django 4.2.4 on 2023-08-28 04:49

from django.db import migrations, models
import fiocruz.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos_virtaulS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('user', models.TextField()),
                ('ligante', models.FileField(blank=True, null=True, upload_to=fiocruz.models.ligante_arquivo)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('resultado_final', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Macromoleculas_virtaulS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('rec', models.CharField(max_length=200)),
                ('rec_fld', models.FileField(upload_to='macromoleculas_virtualS')),
                ('ligante_original', models.CharField(blank=True, max_length=200, null=True)),
                ('rmsd_redoking', models.CharField(blank=True, max_length=200, null=True)),
                ('energia_orinal', models.CharField(blank=True, max_length=200, null=True)),
                ('gridsize', models.CharField(blank=True, max_length=200, null=True)),
                ('gridcenter', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('role', models.CharField(default='USER', max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
