# Generated by Django 4.2.4 on 2024-10-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='macroprepare',
            table='macro_prepare',
        ),
    ]
