# Generated by Django 4.2.4 on 2023-08-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arquivos_virtauls',
            table='Arquivos_virtaulS',
        ),
    ]
