# Generated by Django 4.2.4 on 2023-08-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0002_alter_arquivos_virtauls_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
