# Generated by Django 4.2.4 on 2023-08-28 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0003_delete_usercustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('role', models.CharField(default='USER', max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
