# Generated by Django 4.2.4 on 2023-09-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0005_alter_arquivos_virtauls_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivos_virtauls',
            name='resultado_final',
        ),
        migrations.AddField(
            model_name='arquivos_virtauls',
            name='dada_docking',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
