# Generated by Django 4.2.4 on 2023-09-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0007_remove_arquivos_virtauls_dada_docking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivos_virtauls',
            name='resultado_final',
        ),
    ]
