# Generated by Django 4.2.4 on 2023-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0008_remove_arquivos_virtauls_resultado_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivos_virtauls',
            name='resultado_final',
            field=models.TextField(blank=True, null=True),
        ),
    ]
