# Generated by Django 4.2.4 on 2023-09-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0010_rename_username_usercustom_firtname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='firtname',
            new_name='firstname',
        ),
    ]
