# Generated by Django 4.2.4 on 2023-09-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0011_rename_firtname_usercustom_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='firstname',
            new_name='username',
        ),
    ]
