# Generated by Django 4.2.4 on 2023-09-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0012_rename_firstname_usercustom_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='username',
            new_name='firstname',
        ),
    ]
