# Generated by Django 4.2.4 on 2023-09-14 06:17

from django.db import migrations, models
import fiocruz.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0013_rename_username_usercustom_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro_Prepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('rec', models.CharField(max_length=200)),
                ('recptorpdb', models.FileField(upload_to=fiocruz.models.arquivo)),
                ('recptorpdbqt', models.FileField(upload_to=fiocruz.models.arquivo)),
                ('ligantepdb', models.FileField(upload_to=fiocruz.models.arquivo)),
                ('centerX', models.FloatField(null=True)),
                ('centerY', models.FloatField(null=True)),
                ('centerZ', models.FloatField(null=True)),
                ('sizeX', models.FloatField(null=True)),
                ('sizeY', models.FloatField(null=True)),
                ('sizeZ', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='arquivos_virtauls',
            name='resultado_final',
            field=models.TextField(default='Sem resultados'),
        ),
    ]
