# Generated by Django 4.2.4 on 2023-09-23 03:53

from django.db import migrations, models
import fiocruz.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0014_macro_prepare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='firstname',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macromoleculas_virtauls',
            name='rec_fld',
            field=models.FileField(upload_to=fiocruz.models.arquivo_macro),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
