# Generated by Django 4.2.4 on 2023-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0015_remove_usercustom_firstname_usercustom_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='role',
            field=models.CharField(default='USER', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
