# Generated by Django 4.2.4 on 2023-10-27 04:12

from django.db import migrations, models
import fiocruz.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0016_alter_usercustom_deleted_alter_usercustom_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macromoleculas_Sem_Redocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('rec', models.CharField(max_length=200)),
                ('rec_fld', models.FileField(upload_to=fiocruz.models.arquivo_macro_SR)),
                ('gridsize', models.CharField(blank=True, max_length=200, null=True)),
                ('gridcenter', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Macromoleculas_Sem_Redocking',
            },
        ),
        migrations.DeleteModel(
            name='Testes',
        ),
        migrations.RemoveField(
            model_name='macro_prepare',
            name='centerX',
        ),
        migrations.RemoveField(
            model_name='macro_prepare',
            name='centerY',
        ),
        migrations.RemoveField(
            model_name='macro_prepare',
            name='centerZ',
        ),
        migrations.RemoveField(
            model_name='macro_prepare',
            name='sizeX',
        ),
        migrations.RemoveField(
            model_name='macro_prepare',
            name='sizeY',
        ),
        migrations.RemoveField(
            model_name='macro_prepare',
            name='sizeZ',
        ),
        migrations.AddField(
            model_name='arquivos_virtauls',
            name='type',
            field=models.TextField(default='Com Redocking'),
        ),
        migrations.AddField(
            model_name='macro_prepare',
            name='gridcenter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='macro_prepare',
            name='gridsize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
