# Generated by Django 4.2.4 on 2024-01-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiocruz", "0020_usercustom_created_at_usercustom_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
