# Generated by Django 4.2.4 on 2024-03-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiocruz", "0021_alter_usercustom_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivos_virtauls",
            name="redocking",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="arquivos_virtauls",
            name="status",
            field=models.CharField(
                choices=[
                    ("em fila", "Em fila"),
                    ("processando", "Processando"),
                    ("concluido", "Concluído"),
                    ("error", "Erro"),
                ],
                default="em fila",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="arquivos_virtauls",
            name="type",
            field=models.CharField(
                choices=[("vivax", "Vivax"), ("falciparum", "Falciparum")],
                default="vivax",
                max_length=10,
            ),
        ),
        migrations.AlterModelTable(
            name="arquivos_virtauls",
            table="arquivos_virtauls",
        ),
    ]
