# Generated by Django 4.2.4 on 2024-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0022_arquivos_virtauls_redocking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivos_virtauls',
            name='redocking',
        ),
        migrations.AlterField(
            model_name='arquivos_virtauls',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arquivos_virtauls',
            name='type',
            field=models.TextField(default='Com Redocking'),
        ),
        migrations.AlterModelTable(
            name='arquivos_virtauls',
            table='Arquivos_virtaulS',
        ),
    ]
