# Generated by Django 4.2.4 on 2024-03-13 18:03

from django.db import migrations, models
import django.db.models.deletion
import fiocruz.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiocruz', '0023_remove_arquivos_virtauls_redocking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Plasmodocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ligante', models.FileField(blank=True, null=True, upload_to=fiocruz.models.ligante_arquivo)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('resultado_final', models.TextField(default='Sem resultados')),
                ('status', models.CharField(choices=[('em fila', 'Em fila'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('error', 'Erro')], default='em fila', max_length=20)),
                ('type', models.CharField(choices=[('vivax', 'Vivax'), ('falciparum', 'Falciparum')], default='Falciparum', max_length=10)),
                ('redocking', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiocruz.usercustom')),
            ],
            options={
                'db_table': 'process_plasmodocking',
            },
        ),
        migrations.DeleteModel(
            name='Arquivos_virtaulS',
        ),
    ]
