# Generated by Django 4.2.4 on 2024-04-29 18:15

from django.db import migrations, models
import fiocruz.models


class Migration(migrations.Migration):
    dependencies = [
        ("fiocruz", "0025_alter_process_plasmodocking_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Macromoleculas_Vivax_CR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("rec", models.CharField(max_length=200)),
                ("rec_fld", models.FileField(upload_to=fiocruz.models.arquivo_macro)),
                (
                    "ligante_original",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "rmsd_redoking",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "energia_orinal",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gridsize", models.CharField(blank=True, max_length=200, null=True)),
                ("gridcenter", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
