version: '3.8'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - database:/var/lib/postgresql/data
    restart: always  # Reinicia automaticamente o contêiner

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    depends_on:
      - db
    restart: always  # Reinicia automaticamente o contêiner

  django:
    build: .
    command: >
      sh -c "env
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/www/server:rw
      - user_data:/var/www/Plasmodocking:rw
      - ./media/macromoleculas/:/var/www/server/media/macromoleculas/:rw
      - proces_data:/var/www/server/media/plasmodocking:rw
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - db
    restart: always  # Reinicia automaticamente o contêiner

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Web interface
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    restart: always  # Reinicia automaticamente o contêiner

  celery:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/var/www/server:rw
      - ./media/macromoleculas/:/var/www/server/media/macromoleculas/:rw
      - user_data:/var/www/Plasmodocking:rw
      - proces_data:/var/www/server/media/plasmodocking:rw
    depends_on:
      - django
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=djangoAPI.settings
      - NVIDIA_VISIBLE_DEVICES=all
    command: >
      sh -c "celery -A djangoAPI worker --loglevel=info" --concurrency=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    restart: always  # Reinicia automaticamente o contêiner

volumes:
  database:
  rabbitmq_data:
  user_data:
  proces_data:
