version: '3.8'

services:
  autodockgpu:
    image: autodockgpu_image
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: >
      /home/autodockgpu/AutoDock-GPU/bin/autodock_gpu_128wi
    volumes:
      - ./data:/data

