name: PlasmodockingB Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: set macromoleculas
      run: cp -r /home/cebio/plasmodocking/media/macromoleculas ./
      
    - name: Run conteiner
      run: docker compose up -d --build
